version: '3.8'
services:
  web:
    build:
      context: ./web
    ports:
      - "5050:5050"
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
    depends_on:
      - redis
  redis:
    image: redis:alpine
