version: '3.8'
services:
  web:
    build:
      context: ./web
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: redis:alpine
